// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Tue Oct  6 15:21:54 2026

teste teste_inst
(
	.KEY0(KEY0_sig) ,	// input  KEY0_sig
	.CLOCK_50(CLOCK_50_sig) ,	// input  CLOCK_50_sig
	.KEY1(KEY1_sig) ,	// input  KEY1_sig
	.LCD_DATA(LCD_DATA_sig) ,	// output [7:0] LCD_DATA_sig
	.LCD_EN(LCD_EN_sig) ,	// output  LCD_EN_sig
	.LCD_RW(LCD_RW_sig) ,	// output  LCD_RW_sig
	.LCD_RS(LCD_RS_sig) ,	// output  LCD_RS_sig
	.LCD_ON(LCD_ON_sig) 	// output  LCD_ON_sig
);

